version: '3.8'

services:
  app:
    image: sofiabarbirato/demo:latest  
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80" 
    depends_on:
      - db  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - ConnectionStrings__DatabaseConnection=Data Source=oracle-db;User ID=RM551721;Password=020503;Pooling=True;Connection Timeout=60;  # Ajusta a string de conexão para o banco Oracle no contêiner

  db:
    image: oracle/database:19.3.0-ee 
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=020503  
      - ORACLE_MEM=2GB
    ports:
      - "1521:1521" 
    volumes:
      - oradata:/opt/oracle/oradata  

volumes:
  oradata:
    driver: local  
